[versions]
godot-kotlin-jvm-utilities = "0.0.4"
kotlin = "1.9.23"
jvmToolchainVersion = "17"

godot-kotlin-jvm="0.9.1-4.2.2" # https://github.com/utopia-rise/godot-kotlin-jvm/releases

kotlinx-coroutines-core="1.8.0" # https://github.com/Kotlin/kotlinx.coroutines/releases
kotlinx-datetime = "0.6.0" # https://github.com/Kotlin/kotlinx-datetime/releases

maven-publish="0.28.0"
grgit="5.2.2"

[libraries]
godot-kotlin-jvm = { group = "com.utopia-rise", name = "godot-library-release", version.ref = "godot-kotlin-jvm" }

kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }

maven-publish = { group = "com.vanniktech", name = "gradle-maven-publish-plugin", version.ref = "maven-publish" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
godot-kotlin-jvm = { id = "com.utopia-rise.godot-kotlin-jvm", version.ref = "godot-kotlin-jvm" }
grgit = { id = "org.ajoberstar.grgit", version.ref = "grgit" }
